spring.application.name=mongoDbSpringConfig

server.port=8089
spring.data.mongodb.uri=mongodb://localhost:27017/test

management.endpoints.web.exposure.exclude=loggers,env,beans
management.endpoints.web.base-path=/details
management.endpoints.web.exposure.include=*