version: '3.8'

services:

  app:
    image: metroride-api
    container_name: metroride-app

    ports:
      - "8081:8080"

  monitor:
    image: busybox
    container_name: metroride-monitor

    command: ping app

    depends_on:
      - app