pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'feature/build-setup',
                    url: 'https://github.com/RISHIKANT2/WiproRepo.git'
            }
        }

        stage('Gradle Build') {
            steps {
                dir('MetroRide-Java-API') {
                    bat 'gradlew.bat clean build'
                }
            }
        }

        stage('Archive JAR') {
            steps {
                archiveArtifacts artifacts: 'MetroRide-Java-API/build/libs/*.jar', fingerprint: true
            }
        }
        stage('Health Check') {
            steps {
                dir('MetroRide-Java-API') {
                    bat '.\\health_check.bat'
                }
            }
        }
    }
}