pipeline {
    agent any

    environment {
        IMAGE_NAME = "metroride-api"
        DOCKER_USER = "rishikant2"
        DOCKER_IMAGE = "${DOCKER_USER}/${IMAGE_NAME}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'feature/build-setup',
                    url: 'https://github.com/RISHIKANT2/WiproRepo.git'
            }
        }

        stage('Health Check') {
            steps {
                dir('MetroRide-Java-API') {
                    bat '.\\health_check.bat'
                }
            }
        }

        stage('Gradle Build') {
            steps {
                dir('MetroRide-Java-API') {
                    bat '.\\gradlew.bat clean build'
                }
            }
        }

        stage('Archive JAR') {
            steps {
                archiveArtifacts artifacts: 'MetroRide-Java-API/build/libs/*.jar', fingerprint: true
            }
        }

        stage('Docker Build') {
            steps {
                dir('MetroRide-Java-API') {
                    bat 'docker build -t %DOCKER_IMAGE%:latest .'
                }
            }
        }

        stage('Docker Login') {
            steps {
                echo 'Docker login mock completed successfully'
            }
        }

        stage('Docker Push') {
            steps {
                echo 'Docker push mock completed successfully'
            }
        }
    }
}